// Legacy Express API → Supabase mapping (machine-readable contract index).
export const LEGACY_MAPPING = [
  { legacy: 'POST /api/auth/signup', now: 'supabase.auth.signUp() + handle_new_user() trigger + ensure_business_for_owner() RPC' },
  { legacy: 'POST /api/auth/login', now: 'supabase.auth.signInWithPassword()' },
  { legacy: 'POST /api/auth/pin-login', now: 'Edge Function pin-login (service_role, server-side only)' },
  { legacy: 'GET /api/auth/me', now: 'supabase.auth.getUser() + profiles + user_locations query' },
  { legacy: 'CRUD /api/menu/*', now: 'direct Supabase queries (RLS) — categories/items/variants/addons' },
  { legacy: 'POST /api/orders', now: 'RPC create_order() (trusted pricing)' },
  { legacy: 'PUT /api/orders/:id/status', now: 'RPC transition_order_status() (side effects + idempotency)' },
  { legacy: 'POST /api/orders/:id/pay', now: 'RPC record_payment()' },
  { legacy: 'CRUD /api/tables + QR', now: 'direct queries (RLS); qr_token unique; public route resolves via get_public_menu()' },
  { legacy: 'GET /api/public/storefront/:slug', now: 'RPC get_public_menu(slug) (SECURITY DEFINER, scoped projection)' },
  { legacy: 'POST /api/public/orders', now: 'RPC create_public_order() (trusted pricing, no auth)' },
  { legacy: 'GET /api/public/orders/:id', now: 'RPC get_public_order(order_id) (scoped projection)' },
  { legacy: 'POST /api/inventory/ingredients/:id/restock', now: 'RPC restock_ingredient()' },
  { legacy: 'GET /api/inventory/alerts', now: 'direct query ingredients where stock_qty < low_stock_threshold (RLS)' },
  { legacy: 'GET /api/customers*', now: 'direct queries (RLS) + RPC redeem_loyalty() for redemption' },
  { legacy: 'GET /api/reports/*', now: 'direct aggregate queries (RLS) + RPC report_top_items()' },
  { legacy: 'PUT /api/settings/fee-config', now: 'direct update location_fee_config (RLS owner/manager)' },
  { legacy: 'POST /api/settings/fee-config/reset-period', now: 'RPC reset_fee_period()' },
  { legacy: 'POST /api/notifications/*', now: 'Edge Function send-notification + device_tokens table' },
  { legacy: 'Socket.io order/inventory events', now: 'Supabase Realtime postgres_changes via supabase.channel()' },
  { legacy: 'JWT middleware + locationScope', now: 'Supabase Auth + RLS (auth.uid() → profiles → user_locations)' },
  { legacy: 'Firebase Admin SDK', now: 'Edge Functions + platform push provider (FCM/APNs), no admin backend' },
  { legacy: 'GET /health', now: 'client supabase.from("locations").select("id",{count:"exact",head:true}) connectivity probe' },
] as const;
